### PR TITLE
Add view for AEL game trailers

### PR DESCRIPTION
**Pull request by mechevarria**
Adds a view called **ROM Trailer**, specifically for AEL. Would be great to include a view that has gameplay trailers for AEL, additional artwork, platform icon and details. Also includes a fix for vertical scrollbars not shown.

Alot of the code is ported from [https://github.com/Wintermute0110/skin.estuary.AEL](https://github.com/Wintermute0110/skin.estuary.AEL)

[Preview Video](https://youtu.be/RYwFyrgQ-Rs)

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Looks great!

I made a few changes to bring things a little more in line with the design language of the skin.

Since I don't use AEL, I was making these changes with dummy art / info, so I'm not 100% sure if they work properly. If you could check out the branch linked below and grab me a few screenshots of it actually in action, that would be fantastic. Would also like to hear your opinions on the changes I've made or if there are any bugs.

https://github.com/jurialmunkey/skin.arctic.zephyr.2/tree/mechevarria-master

**Comment by mechevarria** [comment]
It is perfect! I just merged and tested. I attached some screenshots. The formatting of the pictures is way better and more consistent than what I hacked together.

I have a couple extra ideas, like adding the platform icon to the subtitle in the showcase header. In other words, adding to the `Nintendo NES | Nintendo | 1985` line in the last screenshot.

Also adding an Info Wall type view with the same ROM Trailer content on the right.  

But all of that is a different pull request. Thanks!

screenshot1
screenshot2
screenshot3

**Comment by mechevarria** [comment]
Shoot, I did find a visual bug. Sometimes the gameplay video is not the same aspect ratio as the snap so they end up layered. I attached a screenshot. The fix I had was to hide the snap while the trailer is playing. It was in this commit

[https://github.com/jurialmunkey/skin.arctic.zephyr.2/pull/154/commits/66f255e2d9e6ed15449f2fb5c54f5f19a81b3c55](https://github.com/jurialmunkey/skin.arctic.zephyr.2/pull/154/commits/66f255e2d9e6ed15449f2fb5c54f5f19a81b3c55)

bug

**Comment by jurialmunkey** [comment]
> 
> 
> Shoot, I did find a visual bug. Sometimes the gameplay video is not the same aspect ratio as the snap so they end up layered. I attached a screenshot. The fix I had was to hide the snap while the trailer is playing. 

Whoops! I missed a NOT "!" conditional. Fixed and merged.

**Comment by jurialmunkey** [comment]
> 
> 
> It is perfect! I just merged and tested. I attached some screenshots. The formatting of the pictures is way better and more consistent than what I hacked together.

Excellent! Thanks for testing, and, more importantly, for a great initial PR!

> I have a couple extra ideas, like adding the platform icon to the subtitle in the showcase header. In other words, adding to the `Nintendo NES | Nintendo | 1985` line in the last screenshot.
> 
> Also adding an Info Wall type view with the same ROM Trailer content on the right.
> 
> But all of that is a different pull request. Thanks!

Sounds great! When you've got it ready, just submit another PR and I'll review.

**Pull request merged**
