### PR TITLE
:sparkles: - Add Watchlist and Collection buttons to DialogVideoInfo

### PR DESCRIPTION
**Pull request by drinfernoo**
I'd like these to be add/remove based on current status, as well as eventually I'd like to add a "mark as watched"/"mark as unwatched" button, but I don't see a great way to do that logic inside the info dialog.

### CODE REVIEW

**Comment by jurialmunkey** [comment]
You can get the labels and actions by having the detailed item in a hidden container and referencing it with `$INFO[Container(ID).ListItem(-4).Label]` `$INFO[Container(ID).ListItem(-4).FolderPath]`

I've got something coming soon using this method!

**Comment by drinfernoo** [comment]
I... do not know what you mean 😅 Those would be able to tell if an item is watched/unwatched?

**Comment by jurialmunkey** [comment]
When you browse the add-on and click on a movie/tv show, you get a list of different options. In a previous version, I displayed the trakt management functions in that list - when that list is loading, the plugin checks trakt to see if the item is in the collection/watchlist/history and adjusts the labels/actions of the items appropriately (e.g. "Add to" or "Remove from"). You won't be able to see it anymore because I disable it by default now (now you need to add `&manage=True` to the path to show those options). It is possible to put the list in a hidden container and then reference the position that the trakt manager functions would be so that you can get the correct "add" or "remove" label and action.

**Comment by drinfernoo** [comment]
Nice, I'll give that a shot 👍

**Comment by drinfernoo** [comment]
I've somehow just deleted my copies of this, but it seemed like I needed to take another swing anyways, so I went ahead and closed this one for now until I get time to take another look.

**Pull request closed without merging**
