### PR TITLE
:speech_balloon: - Fix Up Next labels

### LINKED ISSUE #178: Incorrect label
https://github.com/jurialmunkey/skin.arctic.zephyr.2/blob/f801c2eca30f88238f6d6bc1c8ce24368df97a10/1080i/script-upnext-upnext.xml#L46

correct... 

`<label>$ADDON[service.upnext 30037] [COLOR $VAR[ColorHighlight]][/COLOR]...</label>`

### PR DESCRIPTION
**Pull request by drinfernoo**
Closes #178 by fixing the labels on the Up Next dialog.

### CODE REVIEW

**Comment by jurialmunkey** [comment]
Excellent! Thanks 😁

**Review by taoxtrece — COMMENTED** [review]
don't need `INFO[Player.TimeRemaing(ss),,]` services 30035,30036 & 30037 already have it included

**Comment by zkvsky** [comment]
@drinfernoo  It's better now but I still have double countdowns ( instead of tripled )

**Comment by michaelarnauts** [comment]
@taoxtrece @barolo I've fixed the remaining double countdowns in #225

**Pull request merged**
