### PR TITLE
Update With TMDB Default Searches

### PR DESCRIPTION
**Pull request by Demonseeed**
Update Template.xml and Overrides.xml with Default Searches for TMDB Movies and Shows. Sorry if I did this wrong, this is my first PR and I was very confused lmao.

I also do not know why there is an indent on the second line of both codes, they don't look like that when I go to edit them.

### CODE REVIEW

**Comment by jurialmunkey** [comment]
> 
> 
> Update Template.xml and Overrides.xml with Default Searches for TMDB Movies and Shows. Sorry if I did this wrong, this is my first PR and I was very confused lmao.

Looks good to me! Well done on submitting your first PR - It can feel a bit daunting and confusing at first, but once you do a couple you realise it is actually pretty simple.

>
> 
> I also do not know why there is an indent on the second line of both codes, they don't look like that when I go to edit them.

The indent is because you are mixing tabs and spaces. If you can update the PR so that all indentation is spaces (i.e. not tabs), then I'll merge.

Also, maybe might be worth adding an option for a `type=person` TMDb search too 😉

**Comment by Demonseeed** [comment]
Thanks! It took me a moment to figure it out, but I think I got the hang of it now. 😄

I fixed the spacing. 

I also added a TMDb people search, but for some reason it doesn’t work when I test it. I’m not sure if it’s because I’m testing it with Kodi on my phone (will have to be tomorrow before I can test on a PC) but when I add the same exact path but replace:
`&amp;` with `&` by manually adding it through AZ2’s menu, it works fine. 🧐

I’ll have to play with it more tomorrow.

**Comment by jurialmunkey** [comment]
Excellent. Looks good! Merged 😁 

> I fixed the spacing. Thanks for that tip! This is my first time really messing with Skinning at all lol so that’s good to know.

Indentation only matters for readability in XML. Also, XML allows mixing tabs and spaces. I prefer using spaces purely for consistency - tab widths can differ between text editors (whereas a space is always the width of one character). The main issue with using tabs exclusively is that spaces tend to accidentally get mixed in without noticing and then you get the indentation issue you had here.

Any decent text editor has options to automatically convert tabs to 4 spaces. I use SublimeText3 and I set that option as default and never have to think about it.

**Comment by Demonseeed** [comment]
Oh cool, I was aware of SublimeText3, but I’ve never used it. I personally always used Notepad++, but tbh I did this entire thing mobile on my iPhone lmao. I’ll check out SublimeText3 next time I get on my computer. 

Also, I’d like to continue doing some PR requests if you don’t mind. I want to learn how to make a skin, which is super daunting as the only real reliable information I have found is the the Kodi Skinning Manual, so editing a skin to start is the best way I’ve found to learn. 

The next thing I would like to look at is adding access to path2 for a custom search list, would you be interested in that? If so, I can open a PR for it. I have thought a bit about how to implement it that would fit the aesthetic of your skin that I would like to run by you.

**Comment by jurialmunkey** [comment]
> 
> 
> Oh cool, I was aware of SublimeText3, but I’ve never used it. I personally always used Notepad++, but tbh I did this entire thing mobile on my iPhone lmao. I’ll check out SublimeText3 next time I get on my computer.
> 
> Also, I’d like to continue doing some PR requests if you don’t mind. I want to learn how to make a skin, which is super daunting as the only real reliable information I have found is the the Kodi Skinning Manual, so editing a skin to start is the best way I’ve found to learn.
> 
> The next thing I would like to look at is adding access to path2 for a custom search list, would you be interested in that? If so, I can open a PR for it. I have thought a bit about how to implement it that would fit the aesthetic of your skin that I would like to run by you.

Sorry I missed this comment.

Haha, that's bold to do a PR from your phone! I don't think I could cope without a proper keyboard!!! Yeah Notepad++ is a great editor. Main reason I use ST3 is for the kodidev plugin.

Definitely YES to more pull requests! It's a great help and much appreciated when users chip in to help improve the skin!

Yes, a way to have access to path2 for search paths would be excellent!

**Pull request merged**
